### ISSUE TITLE
Add  HTML Element Component

### ISSUE THREAD

**Issue by ayaanraj** [multinerd/formio-export#1]
Greetings,
This is an awesome plugin and very useful.

I think you have included all the components, but you have missed out <b>HTML Element Component</b>, if you could add that component in your plugin, it would great.

As HTML Element Component will be very useful to include custom HTML and images as well.

Thank you.

**Comment by multinerd** [comment]
I don’t plan on adding any features as it works out in my use case. 

You can try your luck with the original developer, though he seems be MIA. 

https://github.com/fast-platform/fast-export

**Comment by joakim-emagine** [comment]
> Greetings,
> This is an awesome plugin and very useful.
> 
> I think you have included all the components, but you have missed out HTML Element Component, if you could add that component in your plugin, it would great.
> 
> As HTML Element Component will be very useful to include custom HTML and images as well.
> 
> Thank you.

Did you figure out how to add the Html Element?

**Comment by joakim-emagine** [comment]
Added a content and html component, FYI.

**Comment by multinerd** [comment]
@joakim-emagine if you're willing to submit a PR, i will accept it.

**Comment by multinerd** [comment]
@ayaanraj HTML element is now supported thanks to the PR from @joakim-emagine #8
